name: aws-asignment
on:
  push:
    branches:
    - main
jobs:
     build-and-deploy:
      runs-on: ubuntu-latest
      steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: docker build
        run: sudo docker build -t shubhamasgaonkar/hellonode:latest .

      - name: running docker image
        run: sudo docker login -u ${{ secrets.username }} -p ${{ secrets.password }}

      - name: pushing docker image
        run: |
         sudo docker push shubhamasgaonkar/hellonode:latest

      - name: running docker image
        run: sudo docker run -d -p 80:80 --name my-hello-world shubhamasgaonkar/hellonode:latest

